theme: jekyll-theme-minimal
title: Mechanical Edit
description: Information to help technical writers and editors from Jay Martin.<br>
  <a href="https://www.linkedin.com/in/jayedwardmartin/">View My LinkedIn Profile</a> 
