theme: jekyll-theme-minimal
title: Mechanical Edit and More
description: These pages share with you some information that helped me as a technical writer and editor.<br><br>[View My LinkedIn Profile](https://www.linkedin.com/in/jayedwardmartin)
