theme: jekyll-theme-minimal
title: Mechanical Edit
description: Information to help technical writers and editors, shared by Jay Martin (<a href="https://www.linkedin.com/in/jayedwardmartin/">LinkedIn</a>, <a rel="me" href="https://sfba.social/@italicize">Mastodon</a>).
