theme: jekyll-theme-minimal
title: Mechanical Edit
description: Information to help technical writers and editors, shared by <a href="https://www.linkedin.com/in/jayedwardmartin/">Jay Martin</a>.<br><br><a href="https://www.mechanicaledit.com/samples/index.htm">View My Portfolio</a>
